FROM python:3.11-slim

ENV PYTHONUNBUFFERED=1

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    git \
    vim \
    && rm -rf /var/lib/apt/lists/*

RUN pip install uv

WORKDIR /app

RUN pip install --upgrade pip setuptools wheel

CMD ["/bin/bash"]
